test:
  name: test
  replicaCount: 1
  image:
    repository: testillano/ct-h1mock
    pullPolicy: Never
    tag: latest
  podAnnotations:
    sidecar.istio.io/inject: "true"
  resources: {}

initContainer:
  image:
    repository: busybox
    pullPolicy: IfNotPresent
    tag: latest

h1mock:
  image:
    repository: testillano/h1mock
    tag: latest

  verbosity:
    enabled: true
