apiVersion: v1
kind: Service
metadata:
  name: {{ include "h1mock-chart.fullname" . }}
  labels:
{{ include "h1mock-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: cmd-port
      protocol: TCP
      name: http-port
  selector:
    app.kubernetes.io/name: {{ include "h1mock-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
