apiVersion: v1
kind: Service
metadata:
  name: {{ include "h1mock-chart.name" . }}
  labels:
{{ include "h1mock-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.traffic_port }}
      protocol: TCP
      name: http-traffic
    - port: {{ .Values.service.admin_port }}
      protocol: TCP
      name: http-admin
  selector:
    app.kubernetes.io/name: {{ include "h1mock-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
