apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{ include "h1mock.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.traffic_port }}
      protocol: TCP
      name: http-traffic
    - port: {{ .Values.service.admin_port }}
      protocol: TCP
      name: http-admin
  selector:
    {{- include "h1mock.selectorLabels" . | nindent 4 }}
